import type { TestCase, TestFramework } from '@/types';

function stepComments(tc: TestCase): string {
  return tc.steps.map((s, i) => `  // Step ${i + 1}: ${s}`).join('\n');
}

function playwrightBlock(tc: TestCase): string {
  return [
    `test('${tc.title.replace(/'/g, "\\'")}', async ({ page }) => {`,
    `  // Preconditions: ${tc.preconditions || 'none'}`,
    `  await page.goto('/');`,
    stepComments(tc),
    `  await expect(page.locator('main')).toBeVisible();`,
    `  // Expected: ${tc.expectedResult}`,
    `});`,
  ].join('\n');
}

function seleniumBlock(tc: TestCase): string {
  const method = tc.title.replace(/[^a-zA-Z0-9]+/g, '_').slice(0, 48);
  return [
    `@Test`,
    `public void ${method}() {`,
    `    driver.get(BASE_URL);`,
    `    // Preconditions: ${tc.preconditions || 'none'}`,
    tc.steps.map((s) => `    // ${s}`).join('\n'),
    `    Assert.assertTrue(driver.findElement(By.tagName("body")).isDisplayed());`,
    `    // Expected: ${tc.expectedResult}`,
    `}`,
  ].join('\n');
}

function apiBlock(tc: TestCase): string {
  return [
    `test('${tc.title.replace(/'/g, "\\'")}', async () => {`,
    `  // Preconditions: ${tc.preconditions || 'none'}`,
    `  const res = await fetch(\`\${BASE_URL}/api/resource\`, {`,
    `    method: 'POST',`,
    `    headers: { 'Content-Type': 'application/json' },`,
    `    body: JSON.stringify(payload),`,
    `  });`,
    tc.steps.map((s) => `  // ${s}`).join('\n'),
    `  expect(res.status).toBe(200);`,
    `  // Expected: ${tc.expectedResult}`,
    `});`,
  ].join('\n');
}

function manualBlock(tc: TestCase): string {
  return [
    `## ${tc.title}`,
    `Preconditions: ${tc.preconditions || 'none'}`,
    ...tc.steps.map((s, i) => `${i + 1}. ${s}`),
    `Expected: ${tc.expectedResult}`,
    `[ ] Executed and passed`,
  ].join('\n');
}

export function generateAutomationCode(
  testCases: TestCase[],
  framework: TestFramework
): string {
  if (testCases.length === 0) return '';

  const header =
    framework === 'Manual'
      ? `# Manual execution plan (${testCases.length} cases)\n`
      : `// Generated by QA Copilot — automation preview\n// ${testCases.length} test case(s) · ${framework}\n\n`;

  const blocks =
    framework === 'Playwright'
      ? `import { test, expect } from '@playwright/test';\n\n${testCases.map(playwrightBlock).join('\n\n')}`
      : framework === 'Selenium'
        ? `// Java + Selenium WebDriver\npublic class GeneratedSuite {\n${testCases
            .map(seleniumBlock)
            .map((b) => b.split('\n').map((l) => `    ${l}`).join('\n'))
            .join('\n\n')}\n}`
        : framework === 'API'
          ? `import { test, expect } from '@playwright/test';\n\n${testCases.map(apiBlock).join('\n\n')}`
          : testCases.map(manualBlock).join('\n\n');

  return header + blocks;
}
